import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('serves the modular app and generated bundle', async t => {
  const port = 4189;
  const server = spawn(process.execPath, ['scripts/serve.mjs'], {
    cwd: root,
    env: { ...process.env, PORT: String(port) },
    stdio: ['ignore', 'pipe', 'pipe']
  });
  t.after(() => server.kill());

  await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Server did not start in time.')), 5000);
    server.once('error', reject);
    server.stdout.on('data', chunk => {
      if (chunk.toString().includes('Story Builder:')) {
        clearTimeout(timeout);
        resolve();
      }
    });
  });

  const indexResponse = await fetch(`http://127.0.0.1:${port}/`);
  assert.equal(indexResponse.status, 200);
  assert.match(indexResponse.headers.get('content-type'), /^text\/html/);
  assert.match(await indexResponse.text(), /<script type="module" src="js\/main\.js"><\/script>/);

  const moduleResponse = await fetch(`http://127.0.0.1:${port}/js/main.js`);
  assert.equal(moduleResponse.status, 200);
  assert.match(moduleResponse.headers.get('content-type'), /^text\/javascript/);

  const bundleResponse = await fetch(`http://127.0.0.1:${port}/bundle.html`);
  assert.equal(bundleResponse.status, 200);
  assert.match(await bundleResponse.text(), /Generated by npm run build/);
});
