/**
 * Story tree state management.
 * The story is a directed graph: nodes are story beats, edges are progression.
 * Branching creates a new child node from any existing node.
 * Parallel arcs are separate node chains stored in the `arcs` map.
 */

import store from './store.js';
import { uid } from '../utils/uid.js';

const DEFAULT_ARC_ID = 'arc_main';

const INITIAL_TREE = {
  rootId: null,
  nodes: {},
  activeNodeId: null,
  checkpointIds: [],
  arcs: {
    [DEFAULT_ARC_ID]: { name: 'Main', nodeIds: [], activeNodeId: null }
  },
  activeArcId: DEFAULT_ARC_ID
};

store.init('tree', structuredClone(INITIAL_TREE));

// ─── Node Operations ──────────────────────────────────────────────────────────

/**
 * Create the root node for a new story.
 * @param {object} opts
 * @param {string} opts.narrativeText  Opening narration generated by AI
 * @param {string} opts.locationId
 * @param {string} opts.activeCharacterId
 * @returns {string} rootId
 */
export function initTree(opts = {}) {
  const rootId = uid('node');
  const root = _makeNode(rootId, null, {
    label: 'Story begins',
    narrativeText: opts.narrativeText ?? '',
    deltaText: opts.narrativeText ?? '',
    actorId: 'narrator',
    userInput: '',
    sessionSnapshot: {
      activeCharacterId: opts.activeCharacterId ?? null,
      locationId: opts.locationId ?? null,
      activeArcId: DEFAULT_ARC_ID
    }
  });

  store.set('tree', {
    ...INITIAL_TREE,
    rootId,
    nodes: { [rootId]: root },
    activeNodeId: rootId,
    arcs: {
      [DEFAULT_ARC_ID]: { name: 'Main', nodeIds: [rootId], activeNodeId: rootId }
    }
  });

  return rootId;
}

/**
 * Append a new node as a child of a story node.
 * @param {object} opts
 * @param {string} opts.userInput       What the user typed
 * @param {string} opts.narrativeText   Full story text at this node
 * @param {string} opts.deltaText       Just the new text added here
 * @param {string} opts.actorId         'char_xxx' or 'narrator'
 * @param {object} opts.sessionSnapshot
 * @param {string} [opts.arcId]         Defaults to active arc
 * @param {string} [opts.parentId]      Defaults to the arc's active node
 * @returns {string} new nodeId
 */
export function appendNode(opts) {
  const tree = store.get('tree');
  const arcId = opts.arcId ?? tree.activeArcId;
  const arc = tree.arcs[arcId];
  if (!arc) throw new Error(`Story arc ${arcId} does not exist.`);

  const parentId = opts.parentId ?? arc.activeNodeId;
  const parentNode = tree.nodes[parentId];
  if (!parentNode || !arc.nodeIds.includes(parentId)) {
    throw new Error(`Parent node ${parentId} does not belong to story arc ${arcId}.`);
  }

  const nodeId = uid('node');

  const node = _makeNode(nodeId, parentId, {
    label: opts.userInput?.slice(0, 40) || 'Continue',
    narrativeText: opts.narrativeText,
    deltaText: opts.deltaText,
    actorId: opts.actorId ?? 'narrator',
    userInput: opts.userInput ?? '',
    sessionSnapshot: opts.sessionSnapshot ?? {}
  });

  const updatedParent = { ...parentNode, childIds: [...parentNode.childIds, nodeId] };
  const activateNewNode = tree.activeArcId === arcId && tree.activeNodeId === parentId;

  const updatedArc = {
    ...arc,
    nodeIds: [...arc.nodeIds, nodeId],
    activeNodeId: activateNewNode ? nodeId : arc.activeNodeId
  };

  store.set('tree', {
    ...tree,
    activeNodeId: activateNewNode ? nodeId : tree.activeNodeId,
    nodes: {
      ...tree.nodes,
      [parentId]: updatedParent,
      [nodeId]: node
    },
    arcs: { ...tree.arcs, [arcId]: updatedArc }
  });

  return nodeId;
}

/**
 * Create a branch: a new child from an arbitrary existing node.
 * Sets that new node as the active node in the arc.
 * @param {string} fromNodeId   The node to branch from
 * @param {string} [arcId]      Defaults to active arc
 * @returns {string} new nodeId (empty node — caller fills it after AI response)
 */
export function branchFrom(fromNodeId) {
  const tree = store.get('tree');
  const arcId = tree.activeArcId;
  const arc = tree.arcs[arcId];
  const nodeId = uid('node');

  const branchNode = _makeNode(nodeId, fromNodeId, {
    label: 'Branch',
    narrativeText: '',
    deltaText: '',
    actorId: 'narrator',
    userInput: '',
    sessionSnapshot: tree.nodes[fromNodeId]?.sessionSnapshot ?? {}
  });

  const fromNode = tree.nodes[fromNodeId];
  const updatedFrom = fromNode
    ? { ...fromNode, childIds: [...fromNode.childIds, nodeId] }
    : null;

  const updatedArc = {
    ...arc,
    nodeIds: [...arc.nodeIds, nodeId],
    activeNodeId: nodeId
  };

  store.set('tree', {
    ...tree,
    activeNodeId: nodeId,
    nodes: {
      ...tree.nodes,
      ...(updatedFrom ? { [fromNodeId]: updatedFrom } : {}),
      [nodeId]: branchNode
    },
    arcs: { ...tree.arcs, [arcId]: updatedArc }
  });

  return nodeId;
}

/**
 * Navigate to an existing node (read-only rewind / exploration).
 * The arc's activeNodeId is updated so the next appendNode branches from here.
 * @param {string} nodeId
 */
export function navigateTo(nodeId) {
  const tree = store.get('tree');
  if (!tree.nodes[nodeId]) return;
  const arcId = Object.entries(tree.arcs).find(([, arc]) => arc.nodeIds.includes(nodeId))?.[0]
    ?? tree.activeArcId;
  store.set('tree', {
    ...tree,
    activeNodeId: nodeId,
    activeArcId: arcId,
    arcs: {
      ...tree.arcs,
      [arcId]: { ...tree.arcs[arcId], activeNodeId: nodeId }
    }
  });
  _restoreNodeContext(nodeId);
}

/**
 * Mark the current active node as a checkpoint.
 */
export function markCheckpoint() {
  const tree = store.get('tree');
  const nodeId = tree.activeNodeId;
  if (!nodeId || tree.checkpointIds.includes(nodeId)) return;
  const node = tree.nodes[nodeId];
  store.set('tree', {
    ...tree,
    checkpointIds: [...tree.checkpointIds, nodeId],
    nodes: { ...tree.nodes, [nodeId]: { ...node, isCheckpoint: true } }
  });
}

/**
 * Update a node's text after streaming completes.
 * @param {string} nodeId
 * @param {string} narrativeText
 * @param {string} deltaText
 */
export function finalizeNodeText(nodeId, narrativeText, deltaText) {
  const tree = store.get('tree');
  const node = tree.nodes[nodeId];
  if (!node) return;
  store.set('tree', {
    ...tree,
    nodes: { ...tree.nodes, [nodeId]: { ...node, narrativeText, deltaText } }
  });
}

// ─── Arc Operations ───────────────────────────────────────────────────────────

/**
 * Create a new parallel arc with its own empty node chain.
 * @param {string} name  Display name, e.g. "The Thief's Tale"
 * @param {object} sessionSnapshot  Initial session context for this arc
 * @returns {string} arcId
 */
export function createArc(name, sessionSnapshot = {}) {
  const tree = store.get('tree');
  const arcId = uid('arc');
  const nodeId = uid('node');

  const rootNode = _makeNode(nodeId, null, {
    label: `${name} begins`,
    narrativeText: '',
    deltaText: '',
    actorId: 'narrator',
    userInput: '',
    sessionSnapshot: { ...sessionSnapshot, activeArcId: arcId }
  });

  store.set('tree', {
    ...tree,
    activeNodeId: nodeId,
    activeArcId: arcId,
    nodes: { ...tree.nodes, [nodeId]: rootNode },
    arcs: {
      ...tree.arcs,
      [arcId]: { name, nodeIds: [nodeId], activeNodeId: nodeId }
    }
  });

  return arcId;
}

/**
 * Switch to a different arc (restores its last active node).
 * @param {string} arcId
 */
export function switchArc(arcId) {
  const tree = store.get('tree');
  const arc = tree.arcs[arcId];
  if (!arc) return;
  store.set('tree', {
    ...tree,
    activeArcId: arcId,
    activeNodeId: arc.activeNodeId
  });
  _restoreNodeContext(arc.activeNodeId);
}

// ─── Read Helpers ─────────────────────────────────────────────────────────────

/** Return ancestry chain from root to the given node (inclusive). */
export function getAncestry(nodeId) {
  const tree = store.get('tree');
  const chain = [];
  const visited = new Set();
  let current = nodeId;
  while (current) {
    if (visited.has(current)) throw new Error(`Story tree cycle detected at ${current}`);
    visited.add(current);
    const node = tree.nodes[current];
    if (!node) break;
    chain.unshift(node);
    current = node.parentId;
  }
  return chain;
}

/**
 * Build the conversation history for prompt construction.
 * Returns the last `limit` nodes from ancestry as { role, content } pairs.
 * @param {string} nodeId
 * @param {number} limit  Max exchange pairs (each = 1 user + 1 assistant)
 * @returns {Array<{role: string, content: string}>}
 */
export function getHistoryMessages(nodeId, limit = 15) {
  const ancestry = getAncestry(nodeId);
  // Keep the generated opening even when the rolling history window advances.
  const opening = ancestry[0]?.parentId === null && ancestry[0]?.deltaText ? ancestry[0] : null;
  const recentLimit = Math.max(0, limit - (opening ? 1 : 0));
  const recent = recentLimit > 0
    ? ancestry.slice(opening ? 1 : 0).slice(-recentLimit)
    : [];
  const windowed = opening ? [opening, ...recent] : recent;

  const messages = [];
  for (const node of windowed) {
    if (node.userInput) {
      messages.push({ role: 'user', content: node.userInput });
    }
    if (node.deltaText) {
      messages.push({ role: 'assistant', content: node.deltaText });
    }
  }
  return messages;
}

export function getActiveNode() {
  const tree = store.get('tree');
  return tree.nodes[tree.activeNodeId] ?? null;
}

export function getTree() {
  return store.get('tree');
}

// ─── Private ──────────────────────────────────────────────────────────────────

function _makeNode(id, parentId, fields) {
  return {
    id,
    parentId: parentId ?? null,
    childIds: [],
    createdAt: Date.now(),
    isCheckpoint: false,
    label: fields.label ?? '',
    narrativeText: fields.narrativeText ?? '',
    deltaText: fields.deltaText ?? '',
    actorId: fields.actorId ?? 'narrator',
    userInput: fields.userInput ?? '',
    sessionSnapshot: fields.sessionSnapshot ?? {}
  };
}

function _restoreNodeContext(nodeId) {
  const tree = store.get('tree');
  const snapshot = tree.nodes[nodeId]?.sessionSnapshot ?? {};

  if (snapshot.activeCharacterId) {
    const characters = store.get('characters');
    if (characters?.all?.[snapshot.activeCharacterId]) {
      store.set('characters', { ...characters, activeId: snapshot.activeCharacterId });
    }
  }

  if (snapshot.locationId) {
    const world = store.get('world');
    if (world?.locations?.[snapshot.locationId]) {
      store.set('world', { ...world, activeLocationId: snapshot.locationId });
    }
  }
}
